### ISSUE TITLE
Installed Failed at the lwip2@1.0.11 install script

### ISSUE THREAD

**Issue by mrj04** [azachar/protractor-screenshoter-plugin#45] opened 2017-06-24 08:56 UTC
node --version
v8.1.2
npm --version
5.0.3
Platform MAC OSX. 

npm install -g protractor-screenshoter-plugin

> lwip2@1.0.11 install /usr/local/lib/node_modules/protractor-screenshoter-plugin/node_modules/lwip2
> node lib/install.js

Installing lwip. If this fails, just install GraphicsMagick (http://www.graphicsmagick.org/).
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.

> lwip@0.0.9 install /usr/local/lib/node_modules/lwip
> node-gyp rebuild

  CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/util.o
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/buffer_worker.o
../src/decoder/buffer_worker.cpp:8:56: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    _height(0), _channels(0), _trans(false), _metadata("") {
                                                       ^
1 warning generated.
n file included from ../src/lib/png/png.c:14:
../src/lib/png/pngpriv.h:805:4: error: ZLIB_VERNUM != PNG_ZLIB_VERNUM       "-I (include path) error: see the notes in pngpriv.h"
#  error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
   ^
1 error generated.
make: *** [Release/obj.target/lwip_decoder/src/lib/png/png.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/Cellar/node/8.1.2/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild
"
gyp ERR! cwd /usr/local/lib/node_modules/lwip
gyp ERR! node -v v8.1.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lwip@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
It seems like lwip failed to be intalled. Please check the errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lwip2@1.0.11 install: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip2@1.0.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by gtroshin** [comment] 2017-06-27 12:50
@mrj04 you can't use 8.1.2 node. Try switch to 7.5.0. 
All tested version of nodes are [here in original comment](https://github.com/EyalAr/lwip/issues/297#issuecomment-300206001).

**Comment by mrj04** [comment] 2017-06-29 21:35
thanks @gtroshin

**Comment by wncm** [comment] 2017-07-13 21:24
A simple workaround for this is to install graphicsmagick. In this case, image-to-ascii won't even try to compile and install lwip (see https://github.com/IonicaBizau/image-to-ascii/blob/master/INSTALLATION.md). It will also speed-up `npm install`.

Also, I made a pull request that makes image-to-ascii an optional dependency: #46 (I assume many of us don't actually use this feature).

**Comment by gtroshin** [comment] 2017-07-17 14:02
@wncm graphicsmagick contains 11 additional dependencies. Does it make sense to use it instead  lwip? Did you try?

**Comment by wncm** [comment] 2017-07-17 18:11
>Did you try

Yep, I've checked on Ubuntu 16.04. After `sudo apt-get install graphicsmagick`, `npm install protractor-screenshoter-plugin` says
```
> lwip2@1.0.11 install /home/wncm/tmp/u56ZD7/node_modules/lwip2
> node lib/install.js

Detected GraphicsMagick. Using it. :)
```
and proceeds without compilation.

**Comment by dudumanbogdan** [comment] 2017-08-24 09:12
I have this version and the issue is reproducible.  Cannot be this package updated to work correctly?

> npm --version
> 5.3.0

and 

> node --version
> v6.9.4

**Comment by btkfrank** [comment] 2017-09-01 00:22
my node version is v7.7.4
OS Mac OSX 10.12.6

And I tried install graphicsmagick via
`# OS X
$ brew install graphicsmagick`

and then `npm install protractor-screenshoter-plugin`

And getting 

`yiyang@yis-macbook-pro ui-test (test_screenshot) $ npm install --save protractor-screenshoter-plugin

> lwip2@1.0.11 install /Users/yiyang/git/sci-qa/ui-test/node_modules/lwip2
> node lib/install.js

Detected GraphicsMagick. Using it. :)
@sci/ops@0.0.1 /Users/yiyang/git/sci-qa/ui-test
└─┬ protractor-screenshoter-plugin@0.3.2
  ├── circular-json@0.3.3
  ├─┬ fs-extra@1.0.0
  │ ├── jsonfile@2.4.0
  │ └── klaw@1.3.1
  ├─┬ image-to-ascii@3.0.7
  │ ├─┬ asciify-pixel-matrix@1.0.8
  │ │ ├─┬ asciify-pixel@1.2.8
  │ │ │ ├─┬ couleurs@6.0.8
  │ │ │ │ ├─┬ ansy@1.0.9
  │ │ │ │ │ ├── ansi-styles@3.2.0
  │ │ │ │ │ ├─┬ custom-return@1.0.6
  │ │ │ │ │ │ └── noop6@1.0.6  deduped
  │ │ │ │ │ ├─┬ supports-color@3.2.3
  │ │ │ │ │ │ └── has-flag@1.0.0
  │ │ │ │ │ └── ul@5.2.12  deduped
  │ │ │ │ ├── iterate-object@1.3.2  deduped
  │ │ │ │ └── typpy@2.3.8  deduped
  │ │ │ ├── deffy@2.2.2  deduped
  │ │ │ ├─┬ pixel-bg@1.0.7
  │ │ │ │ └── pixel-class@1.0.6  deduped
  │ │ │ ├── pixel-class@1.0.6  deduped
  │ │ │ ├─┬ pixel-white-bg@1.0.6
  │ │ │ │ └── pixel-bg@1.0.7  deduped
  │ │ │ └── ul@5.2.12  deduped
  │ │ └── ul@5.2.12  deduped
  │ ├─┬ compute-size@1.0.7
  │ │ ├─┬ fixed-or-percent@1.0.7
  │ │ │ ├─┬ is-percent@1.0.8
  │ │ │ │ └── last-char@1.3.7
  │ │ │ └── percent-value@1.0.6
  │ │ ├─┬ map-o@2.0.7
  │ │ │ └── iterate-object@1.3.2
  │ │ └── ul@5.2.12  deduped
  │ ├─┬ image-parser@1.2.4
  │ │ ├── cb-buffer@2.1.3
  │ │ ├─┬ err@1.1.1
  │ │ │ └── typpy@2.3.8  deduped
  │ │ ├─┬ gm-tools@1.0.7
  │ │ │ ├─┬ gm@1.23.0
  │ │ │ │ ├── array-parallel@0.1.3
  │ │ │ │ ├── array-series@0.1.5
  │ │ │ │ ├── cross-spawn@4.0.2
  │ │ │ │ └─┬ debug@2.2.0
  │ │ │ │   └── ms@0.7.1
  │ │ │ ├── iterate-object@1.3.2  deduped
  │ │ │ ├── pixel-class@1.0.6  deduped
  │ │ │ ├── pngjs@2.3.1
  │ │ │ └─┬ same-time@2.3.3
  │ │ │   └─┬ deffy@2.0.0
  │ │ │     └── typpy@2.3.8  deduped
  │ │ ├─┬ lwipify@2.0.8
  │ │ │ ├─┬ lwip2@1.0.11
  │ │ │ │ ├── err@1.1.1  deduped
  │ │ │ │ └─┬ gm-installed@1.0.6
  │ │ │ │   └── prgm-installed@1.0.7
  │ │ │ ├── noop6@1.0.6  deduped
  │ │ │ ├─┬ tinyreq@3.2.5
  │ │ │ │ ├─┬ assured@1.0.8
  │ │ │ │ │ ├── noop6@1.0.6  deduped
  │ │ │ │ │ └── sliced@1.0.1  deduped
  │ │ │ │ ├─┬ follow-redirects@0.2.0
  │ │ │ │ │ └── stream-consume@0.1.0
  │ │ │ │ ├── noop6@1.0.6  deduped
  │ │ │ │ └── ul@5.2.12  deduped
  │ │ │ └─┬ url-remote@1.1.5
  │ │ │   └─┬ url-local@1.1.5
  │ │ │     └─┬ parse-url@1.3.11
  │ │ │       ├─┬ is-ssh@1.3.0
  │ │ │       │ └── protocols@1.4.5  deduped
  │ │ │       └── protocols@1.4.5
  │ │ ├── noop6@1.0.6
  │ │ └─┬ pixel-class@1.0.6
  │ │   └── deffy@2.2.2  deduped
  │ ├─┬ imgpx@1.0.9
  │ │ ├─┬ lwip-pixels@1.1.6
  │ │ │ └── pixel-class@1.0.6  deduped
  │ │ └── lwipify@2.0.8  deduped
  │ ├─┬ one-by-one@3.2.5
  │ │ ├─┬ obj-def@1.0.5
  │ │ │ └── deffy@2.2.2  deduped
  │ │ └── sliced@1.0.1
  │ ├─┬ terminal-char-width@1.0.6
  │ │ └── is-windows@0.1.1
  │ └─┬ ul@5.2.12
  │   ├─┬ deffy@2.2.2
  │   │ └── typpy@2.3.8  deduped
  │   └─┬ typpy@2.3.8
  │     └─┬ function.name@1.0.8
  │       └── noop6@1.0.6  deduped
  ├── lodash@4.17.4
  ├── moment@2.18.1
  └── screenshoter-report-analyzer@0.3.0`


and then run `protractor protractor.conf.js`

with the following config

`plugins: [{
        package: 'protractor-screenshoter-plugin',
        screenshotPath: './REPORTS/e2e',
        screenshotOnExpect: 'failure+success',
        screenshotOnSpec: 'none',
        withLogs: 'true',
        writeReportFreq: 'asap',
        imageToAscii: 'failure',
        clearFoldersBeforeTest: true
    }],`

I am getting `[15:53:41] E/launcher - Cannot find module 'protractor-screenshoter-plugin'`

**Comment by a-inglese** [comment] 2017-09-26 15:47
Same issue here. 
Using node 6.11.2.
I agree that "image-to-ascii" should be optional, specially if is causing these type of issues

**Comment by azachar** [comment] 2017-12-19 13:58
Closing this in favor of #46

**Closed by azachar** 2017-12-19 13:58 UTC
